### ISSUE TITLE
Updated Alliance Offsets for HudManager

### ISSUE THREAD

**Issue by PunishedPineapple** [Ottermandias/RezPls#6]
It looks like the updated offsets are probably:

```
private const int AllianceMemberOffset = 0x0D24;
private const int AllianceSizeOffset   = 0x0DC4;
```

At least that's what I found that worked for me in my stolen version of your HudManager.

**Comment by Ottermandias** [comment]
I had totally forgotten that I never updated that. I'll see if it works with them today in roulettes and if so push an update, thanks :D

**Comment by Ottermandias** [comment]
Sorry I slept on this for so long and thank you again :D
