### ISSUE TITLE
Updated Offsets for HudManager in FFXIV 6.1

### ISSUE THREAD

**Issue by PunishedPineapple** [Ottermandias/RezPls#7]
If it saves you any time updating for the new patch, this is what I found while updating ReadyCheckHelper.  You might want to double check, since I did this quickly and only made sure that my own stuff worked.

```
private const int GroupMemberOffset    = 0x0CC8;
private const int AllianceMemberOffset = 0x0E14;
private const int AllianceSizeOffset   = 0x0EB4;
private const int GroupMemberSize      = 0x20;
private const int GroupMemberIdOffset  = 0x18;
```

**Comment by Ottermandias** [comment]
It will save time. Double checking alliance raid stuff is just so bothersome :D
Thank you very much. I'll do it faster this time :D

**Comment by Ottermandias** [comment]
I checked them in an alliance raid, they all seem to work fine. Thank you again :)
